
package projeto.cliente1.ws.placa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidadorPlacaServiceImplService", targetNamespace = "http://servidor.projeto/", wsdlLocation = "http://localhost:8080/validarPlaca?wsdl")
public class ValidadorPlacaServiceImplService
    extends Service
{

    private final static URL VALIDADORPLACASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDADORPLACASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName VALIDADORPLACASERVICEIMPLSERVICE_QNAME = new QName("http://servidor.projeto/", "ValidadorPlacaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/validarPlaca?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDADORPLACASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        VALIDADORPLACASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ValidadorPlacaServiceImplService() {
        super(__getWsdlLocation(), VALIDADORPLACASERVICEIMPLSERVICE_QNAME);
    }

    public ValidadorPlacaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDADORPLACASERVICEIMPLSERVICE_QNAME, features);
    }

    public ValidadorPlacaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, VALIDADORPLACASERVICEIMPLSERVICE_QNAME);
    }

    public ValidadorPlacaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDADORPLACASERVICEIMPLSERVICE_QNAME, features);
    }

    public ValidadorPlacaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidadorPlacaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidadorPlacaServiceImpl
     */
    @WebEndpoint(name = "ValidadorPlacaServiceImplPort")
    public ValidadorPlacaServiceImpl getValidadorPlacaServiceImplPort() {
        return super.getPort(new QName("http://servidor.projeto/", "ValidadorPlacaServiceImplPort"), ValidadorPlacaServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidadorPlacaServiceImpl
     */
    @WebEndpoint(name = "ValidadorPlacaServiceImplPort")
    public ValidadorPlacaServiceImpl getValidadorPlacaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor.projeto/", "ValidadorPlacaServiceImplPort"), ValidadorPlacaServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDADORPLACASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw VALIDADORPLACASERVICEIMPLSERVICE_EXCEPTION;
        }
        return VALIDADORPLACASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
