
package projeto.cliente1.ws.cpf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidadorCPFServiceImplService", targetNamespace = "http://servidor.projeto/", wsdlLocation = "http://localhost:8080/validarCPF?wsdl")
public class ValidadorCPFServiceImplService
    extends Service
{

    private final static URL VALIDADORCPFSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDADORCPFSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName VALIDADORCPFSERVICEIMPLSERVICE_QNAME = new QName("http://servidor.projeto/", "ValidadorCPFServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/validarCPF?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDADORCPFSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        VALIDADORCPFSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ValidadorCPFServiceImplService() {
        super(__getWsdlLocation(), VALIDADORCPFSERVICEIMPLSERVICE_QNAME);
    }

    public ValidadorCPFServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDADORCPFSERVICEIMPLSERVICE_QNAME, features);
    }

    public ValidadorCPFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, VALIDADORCPFSERVICEIMPLSERVICE_QNAME);
    }

    public ValidadorCPFServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDADORCPFSERVICEIMPLSERVICE_QNAME, features);
    }

    public ValidadorCPFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidadorCPFServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidadorCPFServiceImpl
     */
    @WebEndpoint(name = "ValidadorCPFServiceImplPort")
    public ValidadorCPFServiceImpl getValidadorCPFServiceImplPort() {
        return super.getPort(new QName("http://servidor.projeto/", "ValidadorCPFServiceImplPort"), ValidadorCPFServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidadorCPFServiceImpl
     */
    @WebEndpoint(name = "ValidadorCPFServiceImplPort")
    public ValidadorCPFServiceImpl getValidadorCPFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor.projeto/", "ValidadorCPFServiceImplPort"), ValidadorCPFServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDADORCPFSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw VALIDADORCPFSERVICEIMPLSERVICE_EXCEPTION;
        }
        return VALIDADORCPFSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
