
package projeto.cliente1.ws.cpf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidadorCPFServiceImpl", targetNamespace = "http://servidor.projeto/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidadorCPFServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarCPF", targetNamespace = "http://servidor.projeto/", className = "projeto.cliente1.ws.cpf.ValidarCPF")
    @ResponseWrapper(localName = "validarCPFResponse", targetNamespace = "http://servidor.projeto/", className = "projeto.cliente1.ws.cpf.ValidarCPFResponse")
    @Action(input = "http://servidor.projeto/ValidadorCPFServiceImpl/validarCPFRequest", output = "http://servidor.projeto/ValidadorCPFServiceImpl/validarCPFResponse")
    public boolean validarCPF(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
